#!/bin/bash

# GENERAL CONFIG START

export NAME="MyName"
export STATUS="ReplaceMe"

# GENERAL CONFIG END

if [[ $1 == "mount" ]];
then

	# SFTP CONFIG START

	export SFTP="127.0.0.1"
	export PORT="22"
	export USR="user"
	export DIR="chat"

	#SFTP CONFIG END

	mkdir -p ~/.cache/chat
	echo "connecting to $SFTP"
	sshfs -p $PORT $USR@$SFTP:$DIR ~/.cache/chat

elif [[ $1 == "chat" ]]; 
then
	echo "Shitchat (sekurity +99999)"
	echo "--------------------------"
	
	if [[ ! -f ~/.cache/chat/main ]];
	then
		echo "configure and run \"./chat mount\" to point to a directory containing a plain text file called \"main\" on a remote SFTP server first"
		exit
	fi

	while :
	do
		echo "writing user profile..."
		mkdir -p ~/.cache/chat/.users
		touch ~/.cache/chat/.users/$NAME
		echo "Name: $NAME" > ~/.cache/chat/.users/$NAME
		echo "Status: $STATUS" >> ~/.cache/chat/.users/$NAME
		echo -n "Last login: " >> ~/.cache/chat/.users/$NAME
		date >> ~/.cache/chat/.users/$NAME
		echo "Currently: Online" >> ~/.cache/chat/.users/$NAME
		echo " "
		echo "reading files..."
		echo " "
		ls ~/.cache/chat/
		echo " "
		echo "Wich chat room would you like to enter? (you can create new ones)"
		echo " "
		read -r -e CHAT

		while :
		do
			clear
			watch -n 1 "cat ~/.cache/chat/$CHAT | tail -n $(($LINES - 2))"
			echo "-------"
			echo "msgbox: "
			read -r -e MAIN
			echo "processing message..."
			if [[ $MAIN == "!exit" ]];
			then
				echo "writing user profile..."
				sed -i '$d' ~/.cache/chat/.users/$NAME
				echo "Currently: Offline" >> ~/.cache/chat/.users/$NAME
				echo "umounting sftp share..."
				umount -l ~/.cache/chat
				exit
			elif [[ $MAIN == "!back" ]];
			then
				break
			elif [[ $MAIN == "!users" ]];
			then
				echo " "
				echo "list of users seen on this server:"
				echo " "
				ls ~/.cache/chat/.users/
				echo " "
				echo "enter a user name, !list or type !cancel"
				while :
				do
					read -r -e USERINPUT
					echo " "
					if [[ $USERINPUT == "!cancel" ]];
					then
						break
					elif [[ $USERINPUT == "!list" ]];
					then
						ls ~/.cache/chat/.users/
						echo " "
					else
						cat ~/.cache/chat/.users/$USERINPUT
						echo " "
					fi
				done
			elif [[ $MAIN == "!help" ]];
			then
				echo " "
				echo "available msgbox commands are: !exit, !back, !users, !help"
				echo " "
				echo "refer to \"help_msgbox\" or the readme at https://github.com/Tina-lel/shitchat/blob/main/README.md for more info"
				echo "press enter to return to the chat screen"
				read 
			else
				date "+%T" >> ~/.cache/chat/$CHAT
				echo -n "$NAME: " >> ~/.cache/chat/$CHAT
				echo "$MAIN" >> ~/.cache/chat/$CHAT
				echo "--------" >> ~/.cache/chat/$CHAT
			fi
		done
	done

elif [[ $1 == "umount" ]];
then
	echo "writing user profile..."
	sed -i '$d' ~/.cache/chat/.users/$NAME
	echo "Currently: Offline" >> ~/.cache/chat/.users/$NAME
	echo "unmounting sftp share..."
	umount -l ~/.cache/chat

elif [[ $1 == "help" ]];
then
	echo "----------------------------------------------------------------------"
	echo "available commands are: chat, mount, umount, help, readme, help_msgbox"
	echo "----------------------------------------------------------------------"
	echo "chat: the main chat"
	echo "mount: mounts the SFTP share"
	echo "umount: unmounts the SFTP share"
	echo "help: displays this message"
	echo "help_msgbox: displays msgbox commands"
	echo "readme: display the Readme file"

elif [[ $1 == "help_msgbox" ]];
then
	echo "----------------------------------------------------------"
	echo "available msgbox commands are: !exit, !back, !users, !help"
	echo "----------------------------------------------------------"

elif [[ $1 == "readme" ]];
then
	curl https://raw.githubusercontent.com/Tina-lel/shitchat/main/README.md

else
	echo "unknown command \"$1\" use \"help\" for a list of commands"

fi
